Models/ContactDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcApplication1.Areas.ContactDetails.Models
{
    public class ContactDetails
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Address HomeAddress { get; set; }
        public Phone HomePhone { get; set; }
        public Phone CellPhone { get; set; }
    }

    public class Phone
    {
        public string CountryCode { get; set; }
        public string AreaCode { get; set; }
        public string PhoneNumber { get; set; }
    }

    public class Address
    {
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Line3 { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
    }
}

Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication1.Areas.ContactDetails.Controllers
{
    public class ManagementController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }        

        [HttpPost]
        public ActionResult Index(ContactDetails.Models.ContactDetails details)
        {
            return View(details);
        }        
    }
}

Views/Management/Index.cshtml
@model MvcApplication1.Areas.ContactDetails.Models.ContactDetails
 
@{
    ViewBag.Title = "Index";
}

    @using (Html.BeginForm("Index", "Management", FormMethod.Post))
    {
    <fieldset>
        <legend>ContactDetails</legend>
        <form>
            <table>
                <tr>
                    <td colspan="3">
                        @Html.LabelFor(model => model.FirstName)<br />
                        @Html.TextBoxFor(model => model.FirstName) <br />
                    </td>
                </tr>
                <tr> 
                    <td colspan="3">
                        @Html.LabelFor(model => model.LastName) <br />
                        @Html.TextBoxFor(model => model.LastName) <br />
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        @Html.LabelFor(model => model.Email) <br />
                        @Html.TextBoxFor(model => model.Email) <br />
                    </td>                 
                </tr>
                <tr>
                   <td> @Html.LabelFor(model => model.CellPhone) <br />
                        @Html.TextBoxFor(model => model.CellPhone.AreaCode) 
                        @Html.TextBoxFor(model => model.CellPhone.CountryCode)  
                        @Html.TextBoxFor(model => model.CellPhone.PhoneNumber) </td>
                </tr>
                <tr>
                     
                   <td> @Html.LabelFor(model => model.HomePhone) <br /> 
                        @Html.TextBoxFor(model => model.HomePhone.AreaCode) 
                        @Html.TextBoxFor(model => model.HomePhone.CountryCode) 
                        @Html.TextBoxFor(model => model.HomePhone.PhoneNumber) </td>
                </tr>
                <tr>
                    <td colspan="3">
                        @Html.LabelFor(model => model.HomeAddress.Line1) <br />
                        @Html.TextBoxFor(model => model.HomeAddress.Line1)
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        @Html.LabelFor(model => model.HomeAddress.Line2) <br />
                        @Html.TextBoxFor(model => model.HomeAddress.Line2) 
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        @Html.LabelFor(model => model.HomeAddress.Line3) <br />
                        @Html.TextBoxFor(model => model.HomeAddress.Line3)
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        @Html.LabelFor(model => model.HomeAddress.City) <br />
                        @Html.TextBoxFor(model => model.HomeAddress.City)
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        @Html.LabelFor(model => model.HomeAddress.Province) <br />
                        @Html.TextBoxFor(model => model.HomeAddress.Province)
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        @Html.LabelFor(model => model.HomeAddress.Country) <br />
                        @Html.TextBoxFor(model => model.HomeAddress.Country)
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        @Html.LabelFor(model => model.HomeAddress.PostalCode) <br />
                        @Html.TextBoxFor(model => model.HomeAddress.PostalCode)
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="submit" name="createBtn" value="Create"/>
                    </td>
                </tr>
            </table>
        </form>
    </fieldset>
    }